# Build stage
FROM golang:1.25-alpine AS builder

# Install build dependencies for CGO
RUN apk add --no-cache gcc musl-dev

WORKDIR /build

# Copy and download modules
COPY go.mod go.sum ./
RUN go mod download

# Copy source code (this includes the 'dist' folder generated by build-ui if run from root)
COPY ./ ./

# Build the binary
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -tags with_utls,with_quic,with_clash_api -o /main .

# Final stage
FROM alpine:latest

WORKDIR /

COPY --from=builder /main /freegfw

EXPOSE 80
EXPOSE 443

CMD ["/freegfw"]
